const GET_REQUEST = 'GET_REQUEST';
const GET_SUCCESS = 'GET_SUCCESS';
const GET_FAILD = 'GET_FAILED';;
const USER_SIGNIN = 'USER_SIGNIN';
const USER_SIGNOUT = 'USER_SIGNOUT';
const CREATE_REQUEST = 'CREATE_REQUEST';
const CREATE_SUCCEEDED = 'CREATE_SUCCEEDED';
const CREATE_FAILED = 'CREATE_FAILED';
const UPDATE_USERLIST = 'UPDATE_USERLISTS';

export {
  GET_SUCCESS,
  GET_FAILD,
  GET_REQUEST,
  USER_SIGNIN,
  USER_SIGNOUT,
  CREATE_REQUEST,
  CREATE_SUCCEEDED,
  CREATE_FAILED,
  UPDATE_USERLIST
};
